Vagrant.configure("2") do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.box = "centos/7"

  # ambari
  config.vm.define "ambari" do |node|
    node.vm.hostname = "ambari"
    node.vm.network "private_network", ip: "192.168.99.100"
    node.vm.network "forwarded_port", host: 8080, guest: 8080
    #node.vm.network "forwarded_port", host: 8440, guest: 8440
  end

  # Zookeeper
  (1..3).each do |i|
    config.vm.define "zookeeper#{i}" do |node|
      node.vm.hostname = "zookeeper#{i}"
      node.vm.network "private_network", ip: "192.168.99.11#{i}"
    end
  end

  # datanode
  (1..3).each do |i|
    config.vm.define "datanode#{i}" do |node|
      node.vm.hostname = "datanode#{i}"
      node.vm.network "private_network", ip: "192.168.99.10#{i}"
    end
  end

  config.vm.provision "shell", inline: "timedatectl set-timezone Asia/Tokyo"
end
